#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import argparse
import datetime
import getpass
import os
import sys
import configparser
import warnings

try:
    import git
    _GIT_AVAILABLE = True
except ImportError:
    _GIT_AVAILABLE = False


def _git_info(path):
    """Return (repo_url, hash_str) for the git repository containing path."""
    if not _GIT_AVAILABLE:
        warnings.warn("`import git` not available.", UserWarning)
        return ("unknown (gitpython not installed)",
                "unknown (gitpython not installed)")
    try:
        repo = git.Repo(os.path.dirname(path), search_parent_directories=True)
        try:
            repo_url = repo.remotes.origin.url
        except AttributeError:
            repo_url = "unknown (no remote 'origin')"
        hash_str = repo.head.object.hexsha[:10]
        if len(repo.git.ls_files(m=True)) > 0:
            warnings.warn(
                "Dirty worktree in git repository! Check `git status`",
                UserWarning,
            )
            hash_str += " (dirty worktree)"
        return (repo_url, hash_str)
    except git.InvalidGitRepositoryError:
        warnings.warn("Not inside a git repository.", UserWarning)
        return ("unknown (not a git repository)",
                "unknown (not a git repository)")


def _provenance_comment(template_abs, script_abs, argv):
    """Return a #-prefixed comment block recording provenance of the output file."""
    template_repo_url, template_hash = _git_info(template_abs)
    script_repo_url, script_hash = _git_info(script_abs)

    lines = [
        "",
        "# " + "-" * 75,
        "# Generated by adapt_enkfpf_par.py",
        f"# Date            : {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"# User            : {getpass.getuser()}",
        f"# Command         : {' '.join(argv)}",
        f"# Template        : {template_abs}",
        f"# template-git-repo : {template_repo_url}",
        f"# template-git-hash : {template_hash}",
        f"# Script          : {script_abs}",
        f"# script-git-repo : {script_repo_url}",
        f"# script-git-hash : {script_hash}",
        "# " + "-" * 75,
    ]
    return "\n".join(lines) + "\n"


def adapt_enkfpf_par(
    output=None,
    pf_problemname=None,
    pf_nprocs=None,
    pf_starttime=None,
    pf_dt=None,
    pf_endtime=None,
    pf_simtime=None,
    pf_updateflag=None,
    pf_gwmasking=None,
    pf_paramupdate=None,
    pf_paramupdate_frequency=None,
    pf_dampingfactor_param=None,
    pf_dampingfactor_state=None,
    pf_damping_switch_sm=None,
    pf_aniso_perm_y=None,
    pf_aniso_perm_z=None,
    pf_aniso_use_parflow=None,
    pf_printensemble=None,
    pf_t_printensemble=None,
    pf_printstat=None,
    pf_paramprintensemble=None,
    pf_paramprintstat=None,
    pf_olfmasking=None,
    pf_olfmasking_param=None,
    pf_olfmasking_depth=None,
    clm_problemname=None,
    clm_nprocs=None,
    clm_update_swc=None,
    clm_update_texture=None,
    clm_update_T=None,
    clm_print_swc=None,
    clm_print_et=None,
    clm_print_inc=None,
    clm_statevec_allcol=None,
    clm_statevec_colmean=None,
    clm_statevec_only_active=None,
    clm_statevec_max_layer=None,
    clm_t_printensemble=None,
    clm_watmin_switch=None,
    clm_swc_mask_snow=None,
    clm_T_mask_snow=None,
    clm_update_tws=None,
    clm_increment_type=None,
    clm_print_da_hist_file=None,
    cosmo_nprocs=None,
    cosmo_dtmult=None,
    da_outdir=None,
    da_nreal=None,
    da_startreal=None,
    da_da_interval=None,
    da_da_interval_final=None,
    da_flexible_da_interval=None,
    da_stat_dumpoffset=None,
    da_screen_wrapper=None,
    da_point_obs=None,
    da_obs_interp_switch=None,
    da_max_inc=None,
    da_TWS_smoother=None,
    da_state_setup=None,
    da_update_snow=None,
    da_remove_mean=None,
    da_exclude_greenland=None,
    da_set_zero_start=None,
    da_crns_flag=None,
    da_crns_bd=None,
    da_da_crns_depth_tol=None,
    da_print_obs_index=None,
):
    template_abs = os.path.abspath("enkfpf.par")

    config = configparser.ConfigParser()
    config.optionxform = str
    config.read("enkfpf.par")

    if pf_problemname is not None:
        config["PF"]["problemname"] = str(pf_problemname)
    if pf_nprocs is not None:
        config["PF"]["nprocs"] = str(pf_nprocs)
    if pf_starttime is not None:
        config["PF"]["starttime"] = str(pf_starttime)
    if pf_dt is not None:
        config["PF"]["dt"] = str(pf_dt)
    if pf_endtime is not None:
        config["PF"]["endtime"] = str(pf_endtime)
    if pf_simtime is not None:
        config["PF"]["simtime"] = str(pf_simtime)
    if pf_updateflag is not None:
        config["PF"]["updateflag"] = str(pf_updateflag)
    if pf_gwmasking is not None:
        config["PF"]["gwmasking"] = str(pf_gwmasking)
    if pf_paramupdate is not None:
        config["PF"]["paramupdate"] = str(pf_paramupdate)
    if pf_paramupdate_frequency is not None:
        config["PF"]["paramupdate_frequency"] = str(pf_paramupdate_frequency)
    if pf_dampingfactor_param is not None:
        config["PF"]["dampingfactor_param"] = str(pf_dampingfactor_param)
    if pf_dampingfactor_state is not None:
        config["PF"]["dampingfactor_state"] = str(pf_dampingfactor_state)
    if pf_damping_switch_sm is not None:
        config["PF"]["damping_switch_sm"] = str(pf_damping_switch_sm)
    if pf_aniso_perm_y is not None:
        config["PF"]["aniso_perm_y"] = str(pf_aniso_perm_y)
    if pf_aniso_perm_z is not None:
        config["PF"]["aniso_perm_z"] = str(pf_aniso_perm_z)
    if pf_aniso_use_parflow is not None:
        config["PF"]["aniso_use_parflow"] = str(pf_aniso_use_parflow)
    if pf_printensemble is not None:
        config["PF"]["printensemble"] = str(pf_printensemble)
    if pf_t_printensemble is not None:
        config["PF"]["t_printensemble"] = str(pf_t_printensemble)
    if pf_printstat is not None:
        config["PF"]["printstat"] = str(pf_printstat)
    if pf_paramprintensemble is not None:
        config["PF"]["paramprintensemble"] = str(pf_paramprintensemble)
    if pf_paramprintstat is not None:
        config["PF"]["paramprintstat"] = str(pf_paramprintstat)
    if pf_olfmasking is not None:
        config["PF"]["olfmasking"] = str(pf_olfmasking)
    if pf_olfmasking_param is not None:
        config["PF"]["olfmasking_param"] = str(pf_olfmasking_param)
    if pf_olfmasking_depth is not None:
        config["PF"]["olfmasking_depth"] = str(pf_olfmasking_depth)

    if clm_problemname is not None:
        config["CLM"]["problemname"] = str(clm_problemname)
    if clm_nprocs is not None:
        config["CLM"]["nprocs"] = str(clm_nprocs)
    if clm_update_swc is not None:
        config["CLM"]["update_swc"] = str(clm_update_swc)
    if clm_update_texture is not None:
        config["CLM"]["update_texture"] = str(clm_update_texture)
    if clm_update_T is not None:
        config["CLM"]["update_T"] = str(clm_update_T)
    if clm_print_swc is not None:
        config["CLM"]["print_swc"] = str(clm_print_swc)
    if clm_print_et is not None:
        config["CLM"]["print_et"] = str(clm_print_et)
    if clm_print_inc is not None:
        config["CLM"]["print_inc"] = str(clm_print_inc)
    if clm_statevec_allcol is not None:
        config["CLM"]["statevec_allcol"] = str(clm_statevec_allcol)
    if clm_statevec_colmean is not None:
        config["CLM"]["statevec_colmean"] = str(clm_statevec_colmean)
    if clm_statevec_only_active is not None:
        config["CLM"]["statevec_only_active"] = str(clm_statevec_only_active)
    if clm_statevec_max_layer is not None:
        config["CLM"]["statevec_max_layer"] = str(clm_statevec_max_layer)
    if clm_t_printensemble is not None:
        config["CLM"]["t_printensemble"] = str(clm_t_printensemble)
    if clm_watmin_switch is not None:
        config["CLM"]["watmin_switch"] = str(clm_watmin_switch)
    if clm_swc_mask_snow is not None:
        config["CLM"]["swc_mask_snow"] = str(clm_swc_mask_snow)
    if clm_T_mask_snow is not None:
        config["CLM"]["T_mask_snow"] = str(clm_T_mask_snow)
    if clm_update_tws is not None:
        config["CLM"]["update_tws"] = str(clm_update_tws)
    if clm_increment_type is not None:
        config["CLM"]["increment_type"] = str(clm_increment_type)
    if clm_print_da_hist_file is not None:
        config["CLM"]["print_da_hist_file"] = str(clm_print_da_hist_file)

    if cosmo_nprocs is not None:
        config["COSMO"]["nprocs"] = str(cosmo_nprocs)
    if cosmo_dtmult is not None:
        config["COSMO"]["dtmult"] = str(cosmo_dtmult)

    if da_outdir is not None:
        config["DA"]["outdir"] = str(da_outdir)
    if da_nreal is not None:
        config["DA"]["nreal"] = str(da_nreal)
    if da_startreal is not None:
        config["DA"]["startreal"] = str(da_startreal)
    if da_da_interval is not None:
        config["DA"]["da_interval"] = str(da_da_interval)
    if da_da_interval_final is not None:
        config["DA"]["da_interval_final"] = str(da_da_interval_final)
    if da_flexible_da_interval is not None:
        config["DA"]["flexible_da_interval"] = str(da_flexible_da_interval)
    if da_stat_dumpoffset is not None:
        config["DA"]["stat_dumpoffset"] = str(da_stat_dumpoffset)
    if da_screen_wrapper is not None:
        config["DA"]["screen_wrapper"] = str(da_screen_wrapper)
    if da_point_obs is not None:
        config["DA"]["point_obs"] = str(da_point_obs)
    if da_obs_interp_switch is not None:
        config["DA"]["obs_interp_switch"] = str(da_obs_interp_switch)
    if da_max_inc is not None:
        config["DA"]["max_inc"] = str(da_max_inc)
    if da_TWS_smoother is not None:
        config["DA"]["TWS_smoother"] = str(da_TWS_smoother)
    if da_state_setup is not None:
        config["DA"]["state_setup"] = str(da_state_setup)
    if da_update_snow is not None:
        config["DA"]["update_snow"] = str(da_update_snow)
    if da_remove_mean is not None:
        config["DA"]["remove_mean"] = str(da_remove_mean)
    if da_exclude_greenland is not None:
        config["DA"]["exclude_greenland"] = str(da_exclude_greenland)
    if da_set_zero_start is not None:
        config["DA"]["set_zero_start"] = str(da_set_zero_start)
    if da_crns_flag is not None:
        config["DA"]["crns_flag"] = str(da_crns_flag)
    if da_crns_bd is not None:
        config["DA"]["crns_bd"] = str(da_crns_bd)
    if da_da_crns_depth_tol is not None:
        config["DA"]["da_crns_depth_tol"] = str(da_da_crns_depth_tol)
    if da_print_obs_index is not None:
        config["DA"]["print_obs_index"] = str(da_print_obs_index)

    script_abs = os.path.abspath(__file__)
    out_path = output if output is not None else "enkfpf.par"
    with open(out_path, "w") as f:
        config.write(f)
        f.write(_provenance_comment(template_abs, script_abs, sys.argv))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Modify enkfpf.par for eCLM-PDAF runs"
    )
    parser.add_argument(
        "-r", "--rundir",
        default=".",
        help="Directory containing enkfpf.par (default: current directory)",
    )
    parser.add_argument(
        "-o", "--output",
        default=None,
        help="Output file path (default: overwrite enkfpf.par in --rundir). "
             "Relative paths are resolved before changing to --rundir.",
    )

    group_pf = parser.add_argument_group(
        "PF",
        "enkfpf.par [PF] section — "
        "https://hpscterrsys.github.io/pdaf/users_guide/running_tsmp_pdaf/input_enkfpf.html#pf",
    )
    group_pf.add_argument("--pf-problemname", type=str, default=None,
                          help="Problem prefix for ParFlow. String values must include "
                               "iniparser quotes, e.g. --pf-problemname '\"myrun\"'")
    group_pf.add_argument("--pf-nprocs", type=int, default=None,
                          help="Number of processors per ParFlow instance")
    group_pf.add_argument("--pf-starttime", type=float, default=None,
                          help="ParFlow start time")
    group_pf.add_argument("--pf-dt", type=float, default=None,
                          help="Inverse factor multiplied to CLM/COSMO time steps")
    group_pf.add_argument("--pf-endtime", type=float, default=None,
                          help="(deprecated) Sets pf-simtime")
    group_pf.add_argument("--pf-simtime", type=float, default=None,
                          help="Total simulation time (ParFlow timing units)")
    group_pf.add_argument("--pf-updateflag", type=int, default=None,
                          help="Type of state vector update (1: pressure, 2/3: soil moisture)")
    group_pf.add_argument("--pf-gwmasking", type=int, default=None,
                          help="Groundwater masking (0: none, 1: saturated, 2: mixed)")
    group_pf.add_argument("--pf-paramupdate", type=int, default=None,
                          help="Parameter update flag (0: none, 1: Ksat, 2: Mannings, ...)")
    group_pf.add_argument("--pf-paramupdate_frequency", type=int, default=None,
                          help="Frequency of parameter updates")
    group_pf.add_argument("--pf-dampingfactor_param", type=float, default=None,
                          help="Damping factor for parameter updates (0.0-1.0)")
    group_pf.add_argument("--pf-dampingfactor_state", type=float, default=None,
                          help="Damping factor for state updates (0.0-1.0)")
    group_pf.add_argument("--pf-damping_switch_sm", type=int, default=None,
                          help="Apply state damping to soil moisture (0: no, 1: yes)")
    group_pf.add_argument("--pf-aniso_perm_y", type=float, default=None,
                          help="Anisotropy factor of Ksat in y-direction")
    group_pf.add_argument("--pf-aniso_perm_z", type=float, default=None,
                          help="Anisotropy factor of Ksat in z-direction")
    group_pf.add_argument("--pf-aniso_use_parflow", type=int, default=None,
                          help="Use heterogeneous anisotropy factors from ParFlow (0/1)")
    group_pf.add_argument("--pf-printensemble", type=int, default=None,
                          help="Print updated state for all ensemble members as pfb (0/1)")
    group_pf.add_argument("--pf-t_printensemble", type=int, default=None,
                          help="Timestep for state ensemble output (-2: off, -1: every step)")
    group_pf.add_argument("--pf-printstat", type=int, default=None,
                          help="Print ensemble statistics as pfb (0/1)")
    group_pf.add_argument("--pf-paramprintensemble", type=int, default=None,
                          help="Print updated parameters as pfb (0/1)")
    group_pf.add_argument("--pf-paramprintstat", type=int, default=None,
                          help="Print parameter statistics as pfb (0/1)")
    group_pf.add_argument("--pf-olfmasking", type=int, default=None,
                          help="Overland flow masking (0: none, 1: all surface, 2: pfb, 3: saturated)")
    group_pf.add_argument("--pf-olfmasking_param", type=int, default=None,
                          help="Overland flow masking for parameter update")
    group_pf.add_argument("--pf-olfmasking_depth", type=int, default=None,
                          help="Number of layers to mask in overland flow masking")

    group_clm = parser.add_argument_group(
        "CLM",
        "enkfpf.par [CLM] section — "
        "https://hpscterrsys.github.io/pdaf/users_guide/running_tsmp_pdaf/input_enkfpf.html#clm",
    )
    group_clm.add_argument("--clm-problemname", type=str, default=None,
                           help="Problem prefix for CLM. String values must include "
                                "iniparser quotes, e.g. --clm-problemname '\"clmin\"'")
    group_clm.add_argument("--clm-nprocs", type=int, default=None,
                           help="Number of processors per CLM instance")
    group_clm.add_argument("--clm-update_swc", type=int, default=None,
                           help="Update soil water content (0: none, 1: update, 2/3: CRNS)")
    group_clm.add_argument("--clm-update_texture", type=int, default=None,
                           help="Update soil parameter (0: none, 1: clay/sand, 2-4: CLM5 options)")
    group_clm.add_argument("--clm-update_T", type=int, default=None,
                           help="Update ground/vegetation temperature (0: none, 1: update)")
    group_clm.add_argument("--clm-print_swc", type=int, default=None,
                           help="Print updated SWC for all ensemble members as netcdf (0/1)")
    group_clm.add_argument("--clm-print_et", type=int, default=None,
                           help="Invoke write_clm_statistics (0/1)")
    group_clm.add_argument("--clm-print_inc", type=int, default=None,
                           help="Print analysis increment after SWC update (0/1)")
    group_clm.add_argument("--clm-statevec_allcol", type=int, default=None,
                           help="Use all SWC columns per gridcell in state vector (0/1)")
    group_clm.add_argument("--clm-statevec_colmean", type=int, default=None,
                           help="Use gridcell mean SWC in state vector (0/1)")
    group_clm.add_argument("--clm-statevec_only_active", type=int, default=None,
                           help="Use only hydrologically active columns and layers until bedrock (0/1)")
    group_clm.add_argument("--clm-statevec_max_layer", type=int, default=None,
                           help="Number of layers in state vector")
    group_clm.add_argument("--clm-t_printensemble", type=int, default=None,
                           help="Timestep for state ensemble output (-2: off, -1: every step)")
    group_clm.add_argument("--clm-watmin_switch", type=int, default=None,
                           help="Minimum soil moisture check (0: 0.0, 3: CLM3.5, 5: CLM5.0)")
    group_clm.add_argument("--clm-swc_mask_snow", type=int, default=None,
                           help="Mask columns with snow cover from SWC updates (0/1)")
    group_clm.add_argument("--clm-T_mask_snow", type=int, default=None,
                           help="Temperature mask snow")
    group_clm.add_argument("--clm-update_tws", type=int, default=None,
                           help="Enable TWS/GRACE data assimilation (0: off, 1: on)")
    group_clm.add_argument("--clm-increment_type", type=int, default=None,
                           help="Increment type")
    group_clm.add_argument("--clm-print_da_hist_file", type=int, default=None,
                           help="Write DA history file output (0: off, 1: on)")

    group_cosmo = parser.add_argument_group(
        "COSMO",
        "enkfpf.par [COSMO] section — "
        "https://hpscterrsys.github.io/pdaf/users_guide/running_tsmp_pdaf/input_enkfpf.html#cosmo",
    )
    group_cosmo.add_argument("--cosmo-nprocs", type=int, default=None,
                             help="Number of processors per COSMO instance")
    group_cosmo.add_argument("--cosmo-dtmult", type=int, default=None,
                             help="Number of COSMO time steps per ParFlow time step")

    group_da = parser.add_argument_group(
        "DA",
        "enkfpf.par [DA] section — "
        "https://hpscterrsys.github.io/pdaf/users_guide/running_tsmp_pdaf/input_enkfpf.html#da",
    )
    group_da.add_argument("--da-outdir", type=str, default=None,
                          help="Directory for assimilation output. String values must include "
                               "iniparser quotes, e.g. --da-outdir '\".\"'")
    group_da.add_argument("--da-nreal", type=int, default=None,
                          help="Number of ensemble members (must equal cmd-n_modeltasks)")
    group_da.add_argument("--da-startreal", type=int, default=None,
                          help="Offset added to suffix numbers for input file creation")
    group_da.add_argument("--da-da_interval", type=float, default=None,
                          help="Time interval between DA steps (ParFlow timing units)")
    group_da.add_argument("--da-da_interval_final", type=float, default=None,
                          help="Final da_interval for flexible time stepping")
    group_da.add_argument("--da-flexible_da_interval", type=int, default=None,
                          help="Flexible time stepping (0: fixed, 1: read from obs file)")
    group_da.add_argument("--da-stat_dumpoffset", type=int, default=None,
                          help="File number offset for DA output files (for restarts)")
    group_da.add_argument("--da-screen_wrapper", type=int, default=None,
                          help="Output verbosity (0: none, 1: medium, 2: debug)")
    group_da.add_argument("--da-point_obs", type=int, default=None,
                          help="Use point observations (1) or multi-scale DA (0)")
    group_da.add_argument("--da-obs_interp_switch", type=int, default=None,
                          help="Interpolate simulated measurements to observation location (0/1)")
    group_da.add_argument("--da-max_inc", type=float, default=None,
                          help="Maximum analysis increment as fraction of current state (TWS DA)")
    group_da.add_argument("--da-TWS_smoother", type=int, default=None,
                          help="Use instantaneous (0) or monthly running-mean (1) CLM fields for TWS DA")
    group_da.add_argument("--da-state_setup", type=int, default=None,
                          help="CLM TWS state vector composition (0: subdivided, 1: aggregated, 2: depth-zone)")
    group_da.add_argument("--da-update_snow", type=int, default=None,
                          help="Update snow component during TWS DA (reserved)")
    group_da.add_argument("--da-remove_mean", type=int, default=None,
                          help="Subtract climatological mean before TWS assimilation (reserved)")
    group_da.add_argument("--da-exclude_greenland", type=int, default=None,
                          help="Exclude Greenland from TWS state vector (0/1)")
    group_da.add_argument("--da-set_zero_start", type=int, default=None,
                          help="Timestep to reset running temporal average before first GRACE observation")
    group_da.add_argument("--da-crns_flag", type=int, default=None,
                          help="CRNS observation flag (0: off, 1: ParFlow-based, 2: CLM-based)")
    group_da.add_argument("--da-crns_bd", type=float, default=None,
                          help="Prescribed bulk density for CRNS operator (crns_flag=2)")
    group_da.add_argument("--da-da_crns_depth_tol", type=float, default=None,
                          help="Convergence criterion for CRNS weighting (crns_flag=1)")
    group_da.add_argument("--da-print_obs_index", type=int, default=None,
                          help="Print process-local observation grid index array (0/1)")

    # Check for duplicate flags
    seen_flags = set()
    for token in sys.argv[1:]:
        if token.startswith("-"):
            if token in seen_flags:
                parser.error(f"argument {token} appears more than once")
            seen_flags.add(token)

    args = parser.parse_args()

    # Resolve output path before chdir so relative paths behave as the user expects
    output = os.path.abspath(args.output) if args.output is not None else None

    os.chdir(args.rundir)

    adapt_enkfpf_par(
        output=output,
        **{k: v for k, v in vars(args).items()
           if k.startswith(("pf_", "clm_", "cosmo_", "da_"))},
    )
